package keymap

type linuxKeyMap map[uint32]LinuxKey

type LinuxKey struct {
	Constant    string
	Value       uint32
	Description string
	WindowsKey  uint32
}

// Linux keycode to key details
var linuxKeys = linuxKeyMap{
	53:  {Constant: "Esc", Value: 53, Description: "Esc"},
	122: {Constant: "F1", Value: 122, Description: "F1"},
	120: {Constant: "F2", Value: 120, Description: "F2"},
	99:  {Constant: "F3", Value: 99, Description: "F3"},
	118: {Constant: "F4", Value: 118, Description: "F4"},
	96:  {Constant: "F5", Value: 96, Description: "F5"},
	97:  {Constant: "F6", Value: 97, Description: "F6"},
	98:  {Constant: "F7", Value: 98, Description: "F7"},
	100: {Constant: "F8", Value: 100, Description: "F8"},
	101: {Constant: "F9", Value: 101, Description: "F9"},
	109: {Constant: "F10", Value: 109, Description: "F10"},
	103: {Constant: "F11", Value: 103, Description: "F11"},
	127: {Constant: "F12", Value: 127, Description: "F12"},
	105: {Constant: "PrintScrn", Value: 105, Description: "PrintScrn"},
	107: {Constant: "Scroll Lock", Value: 107, Description: "Scroll Lock"},
	113: {Constant: "Pause", Value: 113, Description: "Pause"},
	50:  {Constant: "`", Value: 50, Description: "`"},
	18:  {Constant: "1", Value: 18, Description: "1"},
	19:  {Constant: "2", Value: 19, Description: "2"},
	20:  {Constant: "3", Value: 20, Description: "3"},
	21:  {Constant: "4", Value: 21, Description: "4"},
	23:  {Constant: "5", Value: 23, Description: "5"},
	22:  {Constant: "6", Value: 22, Description: "6"},
	26:  {Constant: "7", Value: 26, Description: "7"},
	28:  {Constant: "8", Value: 28, Description: "8"},
	25:  {Constant: "9", Value: 25, Description: "9"},
	29:  {Constant: "0", Value: 29, Description: "0"},
	27:  {Constant: "-", Value: 27, Description: "-"},
	24:  {Constant: "=", Value: 24, Description: "="},
	51:  {Constant: "Backspace", Value: 51, Description: "Backspace"},
	114: {Constant: "Insert", Value: 114, Description: "Insert"},
	115: {Constant: "Home", Value: 115, Description: "Home"},
	116: {Constant: "Page Up", Value: 116, Description: "Page Up"},
	71:  {Constant: "Num Lock", Value: 71, Description: "Num Lock"},
	75:  {Constant: "KP /", Value: 75, Description: "KP /"},
	67:  {Constant: "KP *", Value: 67, Description: "KP *"},
	78:  {Constant: "KP -", Value: 78, Description: "KP -"},
	48:  {Constant: "Tab", Value: 48, Description: "Tab"},
	12:  {Constant: "Q", Value: 12, Description: "Q"},
	13:  {Constant: "W", Value: 13, Description: "W"},
	14:  {Constant: "E", Value: 14, Description: "E"},
	15:  {Constant: "R", Value: 15, Description: "R"},
	17:  {Constant: "T", Value: 17, Description: "T"},
	16:  {Constant: "Y", Value: 16, Description: "Y"},
	32:  {Constant: "U", Value: 32, Description: "U"},
	34:  {Constant: "I", Value: 34, Description: "I"},
	31:  {Constant: "O", Value: 31, Description: "O"},
	35:  {Constant: "P", Value: 35, Description: "P"},
	33:  {Constant: "[", Value: 33, Description: "["},
	30:  {Constant: "]", Value: 30, Description: "]"},
	36:  {Constant: "Return", Value: 36, Description: "Return"},
	117: {Constant: "Delete", Value: 117, Description: "Delete"},
	119: {Constant: "End", Value: 119, Description: "End"},
	121: {Constant: "Page Down", Value: 121, Description: "Page Down"},
	89:  {Constant: "KP 7", Value: 89, Description: "KP 7"},
	91:  {Constant: "KP 8", Value: 91, Description: "KP 8"},
	92:  {Constant: "KP 9", Value: 92, Description: "KP 9"},
	69:  {Constant: "KP +", Value: 69, Description: "KP +"},
	57:  {Constant: "Caps Lock", Value: 57, Description: "Caps Lock"},
	0:   {Constant: "A", Value: 0, Description: "A"},
	1:   {Constant: "S", Value: 1, Description: "S"},
	2:   {Constant: "D", Value: 2, Description: "D"},
	3:   {Constant: "F", Value: 3, Description: "F"},
	5:   {Constant: "G", Value: 5, Description: "G"},
	4:   {Constant: "H", Value: 4, Description: "H"},
	38:  {Constant: "J", Value: 38, Description: "J"},
	40:  {Constant: "K", Value: 40, Description: "K"},
	37:  {Constant: "L", Value: 37, Description: "L"},
	41:  {Constant: ";", Value: 41, Description: ";"},
	39:  {Constant: "'", Value: 39, Description: "'"},
	86:  {Constant: "KP 4", Value: 86, Description: "KP 4"},
	87:  {Constant: "KP 5", Value: 87, Description: "KP 5"},
	88:  {Constant: "KP 6", Value: 88, Description: "KP 6"},
	56:  {Constant: "Shift Left", Value: 56, Description: "Shift Left"},
	6:   {Constant: "Z", Value: 6, Description: "Z"},
	7:   {Constant: "X", Value: 7, Description: "X"},
	8:   {Constant: "C", Value: 8, Description: "C"},
	9:   {Constant: "V", Value: 9, Description: "V"},
	11:  {Constant: "B", Value: 11, Description: "B"},
	45:  {Constant: "N", Value: 45, Description: "N"},
	46:  {Constant: "M", Value: 46, Description: "M"},
	43:  {Constant: ",", Value: 43, Description: ","},
	47:  {Constant: ".", Value: 47, Description: "."},
	44:  {Constant: "/", Value: 44, Description: "/"},
	42:  {Constant: "\\", Value: 42, Description: "\\"},
	62:  {Constant: "Cursor Up", Value: 62, Description: "Cursor Up"},
	83:  {Constant: "KP 1", Value: 83, Description: "KP 1"},
	84:  {Constant: "KP 2", Value: 84, Description: "KP 2"},
	85:  {Constant: "KP 3", Value: 85, Description: "KP 3"},
	76:  {Constant: "KP Enter", Value: 76, Description: "KP Enter"},
	54:  {Constant: "Ctrl Left", Value: 54, Description: "Ctrl Left"},
	58:  {Constant: "Logo Left (-> Option)", Value: 58, Description: "Logo Left (-> Option)"},
	55:  {Constant: "Alt Left (-> Command)", Value: 55, Description: "Alt Left (-> Command)"},
	49:  {Constant: "Space", Value: 49, Description: "Space"},
	59:  {Constant: "Cursor Left", Value: 59, Description: "Cursor Left"},
	61:  {Constant: "Cursor Down", Value: 61, Description: "Cursor Down"},
	60:  {Constant: "Cursor Right", Value: 60, Description: "Cursor Right"},
	82:  {Constant: "KP 0", Value: 82, Description: "KP 0"},
	65:  {Constant: "KP .", Value: 65, Description: "KP ."},
}
