package dx11

type D3D_DRIVER_TYPE int

const (
	D3D_DRIVER_TYPE_UNKNOWN D3D_DRIVER_TYPE = iota
	D3D_DRIVER_TYPE_HARDWARE
	D3D_DRIVER_TYPE_REFERENCE
	D3D_DRIVER_TYPE_NULLD3D11_CREATE_DEVICE_SINGLETHREADED
	D3D_DRIVER_TYPE_SOFTWARE
	D3D_DRIVER_TYPE_WARP
)

type D3D_FEATURE_LEVEL uint32

const (
	D3D_FEATURE_LEVEL_1_0_CORE D3D_FEATURE_LEVEL = 0x1000
	D3D_FEATURE_LEVEL_9_1      D3D_FEATURE_LEVEL = 0x9100
	D3D_FEATURE_LEVEL_9_2      D3D_FEATURE_LEVEL = 0x9200
	D3D_FEATURE_LEVEL_9_3      D3D_FEATURE_LEVEL = 0x9300
	D3D_FEATURE_LEVEL_10_0     D3D_FEATURE_LEVEL = 0xa000
	D3D_FEATURE_LEVEL_10_1     D3D_FEATURE_LEVEL = 0xa100
	D3D_FEATURE_LEVEL_11_0     D3D_FEATURE_LEVEL = 0xb000
	D3D_FEATURE_LEVEL_11_1     D3D_FEATURE_LEVEL = 0xb100
	D3D_FEATURE_LEVEL_12_0     D3D_FEATURE_LEVEL = 0xc000
	D3D_FEATURE_LEVEL_12_1     D3D_FEATURE_LEVEL = 0xc100
	D3D_FEATURE_LEVEL_12_2     D3D_FEATURE_LEVEL = 0xc200
)

type D3D_FL9 int32

const (
	D3D_FL9_1_REQ_TEXTURE1D_U_DIMENSION        D3D_FL9 = 2048
	D3D_FL9_3_REQ_TEXTURE1D_U_DIMENSION        D3D_FL9 = 4096
	D3D_FL9_1_REQ_TEXTURE2D_U_OR_V_DIMENSION   D3D_FL9 = 2048
	D3D_FL9_3_REQ_TEXTURE2D_U_OR_V_DIMENSION   D3D_FL9 = 4096
	D3D_FL9_1_REQ_TEXTURECUBE_DIMENSION        D3D_FL9 = 512
	D3D_FL9_3_REQ_TEXTURECUBE_DIMENSION        D3D_FL9 = 4096
	D3D_FL9_1_REQ_TEXTURE3D_U_V_OR_W_DIMENSION D3D_FL9 = 256
	D3D_FL9_1_DEFAULT_MAX_ANISOTROPY           D3D_FL9 = 2
	D3D_FL9_1_IA_PRIMITIVE_MAX_COUNT           D3D_FL9 = 65535
	D3D_FL9_2_IA_PRIMITIVE_MAX_COUNT           D3D_FL9 = 1048575
	D3D_FL9_1_SIMULTANEOUS_RENDER_TARGET_COUNT D3D_FL9 = 1
	D3D_FL9_3_SIMULTANEOUS_RENDER_TARGET_COUNT D3D_FL9 = 4
	D3D_FL9_1_MAX_TEXTURE_REPEAT               D3D_FL9 = 128
	D3D_FL9_2_MAX_TEXTURE_REPEAT               D3D_FL9 = 2048
	D3D_FL9_3_MAX_TEXTURE_REPEAT               D3D_FL9 = 8192
)

type D3D_PRIMITIVE_TOPOLOGY int32

const (
	D3D_PRIMITIVE_TOPOLOGY_UNDEFINED                    D3D_PRIMITIVE_TOPOLOGY = 0
	D3D_PRIMITIVE_TOPOLOGY_POINTLIST                    D3D_PRIMITIVE_TOPOLOGY = 1
	D3D_PRIMITIVE_TOPOLOGY_LINELIST                     D3D_PRIMITIVE_TOPOLOGY = 2
	D3D_PRIMITIVE_TOPOLOGY_LINESTRIP                    D3D_PRIMITIVE_TOPOLOGY = 3
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST                 D3D_PRIMITIVE_TOPOLOGY = 4
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP                D3D_PRIMITIVE_TOPOLOGY = 5
	D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ                 D3D_PRIMITIVE_TOPOLOGY = 10
	D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ                D3D_PRIMITIVE_TOPOLOGY = 11
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ             D3D_PRIMITIVE_TOPOLOGY = 12
	D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ            D3D_PRIMITIVE_TOPOLOGY = 13
	D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST    D3D_PRIMITIVE_TOPOLOGY = 33
	D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST    D3D_PRIMITIVE_TOPOLOGY = 34
	D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST    D3D_PRIMITIVE_TOPOLOGY = 35
	D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST    D3D_PRIMITIVE_TOPOLOGY = 36
	D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST    D3D_PRIMITIVE_TOPOLOGY = 37
	D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST    D3D_PRIMITIVE_TOPOLOGY = 38
	D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST    D3D_PRIMITIVE_TOPOLOGY = 39
	D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST    D3D_PRIMITIVE_TOPOLOGY = 40
	D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST    D3D_PRIMITIVE_TOPOLOGY = 41
	D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 42
	D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 43
	D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 44
	D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 45
	D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 46
	D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 47
	D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 48
	D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 49
	D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 50
	D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 51
	D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 52
	D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 53
	D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 54
	D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 55
	D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 56
	D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 57
	D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 58
	D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 59
	D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 60
	D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 61
	D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 62
	D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 63
	D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST   D3D_PRIMITIVE_TOPOLOGY = 64
	D3D10_PRIMITIVE_TOPOLOGY_UNDEFINED                  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_UNDEFINED
	D3D10_PRIMITIVE_TOPOLOGY_POINTLIST                  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_POINTLIST
	D3D10_PRIMITIVE_TOPOLOGY_LINELIST                   D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_LINELIST
	D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP                  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP
	D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST               D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST
	D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP              D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP
	D3D10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ               D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ
	D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ              D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ
	D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ           D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ
	D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ          D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ
	D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED                  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_UNDEFINED
	D3D11_PRIMITIVE_TOPOLOGY_POINTLIST                  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_POINTLIST
	D3D11_PRIMITIVE_TOPOLOGY_LINELIST                   D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_LINELIST
	D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP                  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP
	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST               D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST
	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP              D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP
	D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ               D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ
	D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ              D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ
	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ           D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ
	D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ          D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ
	D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST  D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST
	D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST D3D_PRIMITIVE_TOPOLOGY = D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST
)

type D3D_SRV_DIMENSION uint32

const (
	D3D_SRV_DIMENSION_UNKNOWN              D3D_SRV_DIMENSION = 0
	D3D_SRV_DIMENSION_BUFFER               D3D_SRV_DIMENSION = 1
	D3D_SRV_DIMENSION_TEXTURE1D            D3D_SRV_DIMENSION = 2
	D3D_SRV_DIMENSION_TEXTURE1DARRAY       D3D_SRV_DIMENSION = 3
	D3D_SRV_DIMENSION_TEXTURE2D            D3D_SRV_DIMENSION = 4
	D3D_SRV_DIMENSION_TEXTURE2DARRAY       D3D_SRV_DIMENSION = 5
	D3D_SRV_DIMENSION_TEXTURE2DMS          D3D_SRV_DIMENSION = 6
	D3D_SRV_DIMENSION_TEXTURE2DMSARRAY     D3D_SRV_DIMENSION = 7
	D3D_SRV_DIMENSION_TEXTURE3D            D3D_SRV_DIMENSION = 8
	D3D_SRV_DIMENSION_TEXTURECUBE          D3D_SRV_DIMENSION = 9
	D3D_SRV_DIMENSION_TEXTURECUBEARRAY     D3D_SRV_DIMENSION = 10
	D3D_SRV_DIMENSION_BUFFEREX             D3D_SRV_DIMENSION = 11
	D3D10_SRV_DIMENSION_UNKNOWN            D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_UNKNOWN
	D3D10_SRV_DIMENSION_BUFFER             D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_BUFFER
	D3D10_SRV_DIMENSION_TEXTURE1D          D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE1D
	D3D10_SRV_DIMENSION_TEXTURE1DARRAY     D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE1DARRAY
	D3D10_SRV_DIMENSION_TEXTURE2D          D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2D
	D3D10_SRV_DIMENSION_TEXTURE2DARRAY     D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2DARRAY
	D3D10_SRV_DIMENSION_TEXTURE2DMS        D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2DMS
	D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY   D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2DMSARRAY
	D3D10_SRV_DIMENSION_TEXTURE3D          D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE3D
	D3D10_SRV_DIMENSION_TEXTURECUBE        D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURECUBE
	D3D10_1_SRV_DIMENSION_UNKNOWN          D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_UNKNOWN
	D3D10_1_SRV_DIMENSION_BUFFER           D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_BUFFER
	D3D10_1_SRV_DIMENSION_TEXTURE1D        D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE1D
	D3D10_1_SRV_DIMENSION_TEXTURE1DARRAY   D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE1DARRAY
	D3D10_1_SRV_DIMENSION_TEXTURE2D        D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2D
	D3D10_1_SRV_DIMENSION_TEXTURE2DARRAY   D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2DARRAY
	D3D10_1_SRV_DIMENSION_TEXTURE2DMS      D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2DMS
	D3D10_1_SRV_DIMENSION_TEXTURE2DMSARRAY D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2DMSARRAY
	D3D10_1_SRV_DIMENSION_TEXTURE3D        D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE3D
	D3D10_1_SRV_DIMENSION_TEXTURECUBE      D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURECUBE
	D3D10_1_SRV_DIMENSION_TEXTURECUBEARRAY D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURECUBEARRAY
	D3D11_SRV_DIMENSION_UNKNOWN            D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_UNKNOWN
	D3D11_SRV_DIMENSION_BUFFER             D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_BUFFER
	D3D11_SRV_DIMENSION_TEXTURE1D          D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE1D
	D3D11_SRV_DIMENSION_TEXTURE1DARRAY     D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE1DARRAY
	D3D11_SRV_DIMENSION_TEXTURE2D          D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2D
	D3D11_SRV_DIMENSION_TEXTURE2DARRAY     D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2DARRAY
	D3D11_SRV_DIMENSION_TEXTURE2DMS        D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2DMS
	D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY   D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE2DMSARRAY
	D3D11_SRV_DIMENSION_TEXTURE3D          D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURE3D
	D3D11_SRV_DIMENSION_TEXTURECUBE        D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURECUBE
	D3D11_SRV_DIMENSION_TEXTURECUBEARRAY   D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_TEXTURECUBEARRAY
	D3D11_SRV_DIMENSION_BUFFEREX           D3D_SRV_DIMENSION = D3D_SRV_DIMENSION_BUFFEREX
)
